# main text of home
title: Kristian Torres Bautista
bio: PhD student @ The Univesity of Alberta

# twitter summary info
#description: I conduct research under the guidance of [Prof. Mauricio Sacchi](https://sites.ualberta.ca/~msacchi/) that focuses on developing deep learning tools for solving inverse problems in seismic imaging and signal processing.
# if it's an external image, update below for true
# better with square images
external-image: false #true
picture: assets/images/kristian_profile.jpeg
#https://avatars.githubusercontent.com/u/40406561?v=4
#assets/images/profile.jpg

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: true

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: assets/cv/KristianTorres_CV_Sep2022.pdf

url: https://kristiantorres.github.io
# your url: https://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: github # enter this from your disqus account
  categories: []#[blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
#instagram: myinstagram
linkedin: kristian-torres
github: kristiantorres
email: torresba@ualberta.ca

authors:
  kristiantorres:
    name: Kristian Torres
    bio: PhD student @ The University of Alberta
    external-image: true
    picture: https://avatars.githubusercontent.com/u/40406561?v=4
    twitter: Kristia55312385
    
# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
#blog: true

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: false

# related posts inside a post?
related: false

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: false

# do you want some animations?
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-paginate-v2

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
